apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trmnl-seedbox.fullname" . }}
  labels:
    {{- include "trmnl-seedbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRMNL_API_KEY: {{ .Values.trmnlApiKey | quote }}
