apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trmnl-cyberpunk.fullname" . }}
  labels:
    {{- include "trmnl-cyberpunk.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRMNL_API_KEY: {{ .Values.trmnlApiKey | quote }}
