{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trmnl-cyberpunk.fullname" . }}
  labels:
    {{- include "trmnl-cyberpunk.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRMNL_API_KEY: {{ .Values.secrets.trmnlApiKey | quote }}
  ICS_URLS: {{ .Values.secrets.icsUrls | default "" | quote }}
  ACTUALBUDGET_KEY: {{ .Values.secrets.actualbudgetKey | default "" | quote }}
  ACTUALBUDGET_SYNC_ID: {{ .Values.secrets.actualbudgetSyncId | default "" | quote }}
  ACTUALBUDGET_PASSWORD: {{ .Values.secrets.actualbudgetPassword | default "" | quote }}
{{- end }}
